name: movies_repository
description: Movies repository
version: 1.0.0

environment:
  sdk: ^3.3.2

dependencies:
  graphql_flutter: ^5.1.2
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
